import{S as y,i as c,a as v}from"./assets/vendor-89feecc5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L=document.querySelector("form"),m=document.querySelector(".gallery"),p=document.querySelector(".loader"),l=document.querySelector(".button-load"),w=new y(".gallery a",{});function x(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}l.classList.add("hidden");d();const b=async({query:s="",page:t=1,perPage:a=40})=>{const o=new URLSearchParams({key:"41516813-c0516a6d5bb80b940f21213c5",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a});try{return(await v.get(`https://pixabay.com/api/?${o}`)).data}catch{c.error({message:"Error",position:"topRight"})}};let u=!1;const q=s=>{let t=1;const a=40;return async()=>{try{const{hits:o,total:e}=await b({page:t,perPage:a,query:s});return t>=Math.ceil(e/a)&&(u=!0),t+=1,o}catch{c.error({message:"Error",position:"topRight"})}}};let n=null;L.addEventListener("submit",async s=>{s.preventDefault();const t=s.currentTarget.elements.query.value;m.innerHTML="",u=!1,n!==null&&l.removeEventListener("click",n);const a=q(t);n=async()=>{x();const o=await a();await E(o),d()},await n(),l.addEventListener("click",async()=>{await n();const e=document.querySelector(".gallery-item").getBoundingClientRect().height;await window.scrollBy(0,e*2)})});function S(s){const t=s.reduce((a,{webformatURL:o,largeImageURL:e,tags:r,likes:i,views:f,comments:g,downloads:h})=>a+`
            <div class="gallery-item">
                <a href="${e}" data-lightbox="image">
                    <img src="${o}" data-source="${e}" alt="${r}">
                </a>
                <div class="text-container">
                    <div class="text-item"><p class="text">Likes:</p>
                        <p class="likes"> ${i}</p></div>
                    <div class="text-item"> <p class="text">Views: </p>
                        <p class="views">${f}</p></div>
                    <div class="text-item"> <p class="text">Comments:</p>
                        <p class="comments"> ${g}</p></div>
                    <div class="text-item"><p class="text">Downloads:</p>
                        <p class="downloads"> ${h}</p></div>
                </div>
            </div>`,"");m.insertAdjacentHTML("beforeend",t)}async function E(s){try{s.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(S(s),w.refresh(),u?(l.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):l.classList.remove("hidden"))}catch{throw d(),c.error({message:"Error",position:"topRight"}),new Error("Error")}}
//# sourceMappingURL=commonHelpers.js.map
